### ISSUE TITLE
Rats getting aggressive where they should not be [Bug / Suggestion]

### ISSUE THREAD

**Issue by KeremKoksal** [AlexModGuy/Rats#98]
First Event: I'm playing Seablock Rustic Waters. I've used an "Automated User" and accidentally set to hit. When the block hit me, all rats gone mad and tried to commit suicide by the machine :) As soon as I understand what's going on I've broke the machine but the remaining rats stayed aggressive on an air block (where the machine was). I've tried to pick them up and put somewhere else but they all returned to them same air block with no rest. I decided to logout and log back in but the client crushed.

Second Event: There is a dungeon close to my base. I've decided to get in and rats probable get aggressive as soon as I get hit. I've found out they got aggressive with the "Rat drowned" messages. (My bad. I didn't block moon door below the base) I've lost all but one. The one with stay here command. But it was still aggressive, shaking like a mad man, even after I've died and returned to base.  

Suggestion: 
1- It would be great to put them on passive, natural or aggressive from their GUI
2- It would be good to have a config file for a blacklist to exclude some of the entities, even blocks (automated users, etc) so they won't get aggressive when their master get hit by them, even they are on aggressive mod.

**Comment by SirAron111** [comment]
On that note i would also like to ask if a config option could be possible to make 2 things variable.
1.	Pirats grifing option I love them but I don’t want to turn the grifing for all mobs to false just so the rats don’t perma bomb stuff.
2.	Also a general option to make wild rats/feral ratlanteans/plague beasts etc not hostile towards each other or other monsters and only towards the player would also be nice. (I am running a Modpack with invasions and the rats sometimes fight each other and normal animals instead of just the player)

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
